import { Cat } from '@/types/cat';
import { Button } from '@/components/ui/button';
import { Card, CardContent, CardFooter } from '@/components/ui/card';
import { deleteCat } from '@/lib/storage';
import { toast } from 'sonner';
import { Printer, Trash2 } from 'lucide-react';

interface CatCardProps {
  cat: Cat;
  onUpdate: () => void;
}

export const CatCard = ({ cat, onUpdate }: CatCardProps) => {
  const handleDelete = () => {
    if (confirm('Are you sure you want to delete this cat?')) {
      deleteCat(cat.id);
      onUpdate();
      toast.success('Cat deleted');
    }
  };

  const handlePrint = () => {
    const printWindow = window.open('', '', 'width=800,height=600');
    if (!printWindow) return;

    const content = `
      <!DOCTYPE html>
      <html>
      <head>
        <title>Cat Info Sheet - ${cat.catName}</title>
        <style>
          body {
            background: #1a0f2e;
            color: #00ff00;
            font-family: 'Courier New', monospace;
            padding: 40px;
            line-height: 1.8;
          }
          .header {
            font-size: 24px;
            text-align: center;
            margin-bottom: 30px;
            border: 2px solid #00ff00;
            padding: 15px;
          }
          .field {
            margin: 20px 0;
            border-left: 3px solid #00ff00;
            padding-left: 15px;
          }
          .label {
            font-weight: bold;
            text-transform: uppercase;
          }
          .value {
            margin-top: 5px;
            padding-left: 10px;
          }
          .photo {
            margin: 20px 0;
            text-align: center;
          }
          .photo img {
            max-width: 400px;
            border: 2px solid #00ff00;
          }
          @media print {
            body {
              -webkit-print-color-adjust: exact;
              print-color-adjust: exact;
            }
          }
        </style>
      </head>
      <body>
        <div class="header">
          ╔════════════════════════════════════╗<br>
          ║  RETRO CHIBI CAT INFO SHEET  ║<br>
          ╚════════════════════════════════════╝
        </div>
        
        <div class="field">
          <div class="label">► CAT ID:</div>
          <div class="value">${cat.catId}</div>
        </div>
        
        <div class="field">
          <div class="label">► OWNER FULL NAME:</div>
          <div class="value">${cat.ownerFullName}</div>
        </div>
        
        <div class="field">
          <div class="label">► CAT NAME:</div>
          <div class="value">${cat.catName}</div>
        </div>
        
        <div class="field">
          <div class="label">► PHYSICAL DESCRIPTION:</div>
          <div class="value">${cat.physical || 'N/A'}</div>
        </div>
        
        <div class="field">
          <div class="label">► MEDICAL DESCRIPTION:</div>
          <div class="value">${cat.medical || 'N/A'}</div>
        </div>
        
        <div class="field">
          <div class="label">► ADDITIONAL INFORMATION:</div>
          <div class="value">${cat.notes || 'N/A'}</div>
        </div>
        
        <div class="field">
          <div class="label">► DATE ADDED:</div>
          <div class="value">${new Date(cat.createdAt).toLocaleDateString()}</div>
        </div>
        
        ${cat.photoUrl ? `
          <div class="photo">
            <img src="${cat.photoUrl}" alt="${cat.catName}" />
          </div>
        ` : ''}
        
        <div style="margin-top: 40px; text-align: center; border-top: 2px solid #00ff00; padding-top: 20px;">
          Generated by Retro Chibi Cat Tracker © ${new Date().getFullYear()}
        </div>
      </body>
      </html>
    `;

    printWindow.document.write(content);
    printWindow.document.close();
    printWindow.focus();
    setTimeout(() => {
      printWindow.print();
    }, 250);
  };

  return (
    <Card className="border-4 border-border retro-shadow overflow-hidden">
      <CardContent className="p-4">
        <div className="flex gap-4 mb-4">
          {cat.photoUrl && (
            <img
              src={cat.photoUrl}
              alt={cat.catName}
              className="w-20 h-20 object-cover rounded-lg border-2 border-border"
            />
          )}
        </div>

        <div className="space-y-2">
          <h3 className="font-bold text-lg">{cat.catName}</h3>
          <p className="text-xs text-muted-foreground">ID: {cat.catId}</p>
          <p className="text-xs">Owner: {cat.ownerFullName}</p>
          
          {cat.physical && (
            <div className="text-xs">
              <span className="font-bold">Physical:</span>
              <p className="mt-1 line-clamp-2">{cat.physical}</p>
            </div>
          )}
          
          {cat.medical && (
            <div className="text-xs">
              <span className="font-bold">Medical:</span>
              <p className="mt-1 line-clamp-2">{cat.medical}</p>
            </div>
          )}
        </div>
      </CardContent>

      <CardFooter className="flex gap-2 p-4 pt-0">
        <Button
          onClick={handlePrint}
          size="sm"
          variant="secondary"
          className="flex-1 text-xs border-2 border-border retro-shadow-hover"
        >
          <Printer className="w-3 h-3 mr-1" />
          Print
        </Button>
        
        <Button
          onClick={handleDelete}
          size="sm"
          variant="destructive"
          className="flex-1 text-xs border-2 border-border retro-shadow-hover"
        >
          <Trash2 className="w-3 h-3 mr-1" />
          Delete
        </Button>
      </CardFooter>
    </Card>
  );
};
